### ISSUE TITLE
Remove gif?

### ISSUE THREAD

**Issue by ray-x** [nacro90/numb.nvim#10]
Not a real issue.
Is it possible to remove the gif from both repo and .git history? Clone the repo took me 5s....
The gif added 3.4MB to the repo. Put gif in a gist would be better.

**Comment by nacro90** [comment]
Done :+1:

**Comment by nacro90** [comment]
Actually, because of my force push to remove the gif from the history, I may have broken the plugin update sequence.

Packer gives an error at update. Can you check if that happens to you.

**Comment by nacro90** [comment]
It solved by removing and re-installing the plugin

**Comment by ray-x** [comment]
Thanks! Looks great.
