### ISSUE TITLE
Unfold code when going into folded line

### ISSUE THREAD

**Issue by JoseConseco** [nacro90/numb.nvim#11]
If I  enter line number which is in folded code block  - numb wont unfold code for preview, but rather it will got to the fold header.
I wish if I enter line number - we could see the unfolded code with line (but if user cancels the  go to line command - the code will remain folded)

**Comment by nacro90** [comment]
This is a good feature/fix candidate. I'm on it :+1: Thanks!

**Comment by nacro90** [comment]
I have made a PR. Can you check that works for you?

While peeking, folding will be disabled temporarily. And if the user confirms, only required folds that are necessary to see new line number, unfolded using `zv`.

**Comment by JoseConseco** [comment]
It works great. Thanks for your time!
