### ISSUE TITLE
[Question] Why vim.cmd("redraw" )

### ISSUE THREAD

**Issue by ray-x** [nacro90/numb.nvim#12]
The reason I am asking is I saw a flicking of vim screen each time I confirm the selection (with large files). If I remove the `redraw` from unpeek. It is ok.
It may be caused by my setup. But is there a specific reason require to redraw the screen?
If it required for some of the setups. Maybe good to have an option for this.

**Comment by nacro90** [comment]
It is required for the update when the user deletes all the numbers from command line (e.g `:5` to `:`)

But as you said, it is not required for confirming the selection. I am removing the `redraw` call from `on_cmdline_exit` :+1:

**Comment by nacro90** [comment]
Can you check if the PR fixes the problem #13

**Comment by ray-x** [comment]
Great job, it is much smoother now.
