### ISSUE TITLE
Suppresses output when multiple commands are used 

### ISSUE THREAD

**Issue by ajitid** [nacro90/numb.nvim#17]
When a mapping like `nnoremap <leader>l <cmd>ls<cr>:b<space>` is used, output of `ls` is shown and Vim leaves cursor in command line mode. With Numb enabled however, output `ls` gets supressed.

**Comment by nacro90** [comment]
I have created a PR. Can you check if that works for you.

Numb was redrawing vim on every `on_cmdline_change`. It redraws only at peeking
state now.
