### ISSUE TITLE
[off-topic/question] how did you get a little symbol to show on the current line? 

### ISSUE THREAD

**Issue by ghost** [nacro90/numb.nvim#22]
As said on the title, how did you get a little arrow to be shown on the current cursor line in the gutter? (as show in the screenshot)
![21-09-04_16h:18](https://user-images.githubusercontent.com/67875888/132097614-5eeff089-7ef6-4746-9c3f-6b4761a771e0.png)

**Comment by nacro90** [comment]
It is a LSP sign for _information_

```viml
sign define LspDiagnosticsSignInformation text=› texthl=LspDiagnosticsSignInformation linehl= numhl=
```

**Comment by ghost** [comment]
*Oh*, didn't knew that.
