### ISSUE TITLE
Show_numbers and show_cursorline are not read from setup ?

### ISSUE THREAD

**Issue by dinkopehar** [nacro90/numb.nvim#26]
I tried to set up `show_numbers` and `show_cursorline` but setting them up in `setup` does not override them:

I'm no expert at Lua, but these lines seem to override `opts`:

https://github.com/nacro90/numb.nvim/blob/d95b7ea62e320b02ca1aa9df3635471a88d6f3b1/lua/numb/init.lua#L58-L59

**Comment by nacro90** [comment]
Those options are `true` by default. Which means if numbers or cursorline is hidden at normal state, they will become visible while peeking. I guess as overriding you meant that setting those options `false`. Setting those opts as `false` means that if they are hidden, they will remain hidden while peeking. If numbers or cursorline are enabled at normal state, the plugin does not hide them.

**Comment by dinkopehar** [comment]
You're correct, I meant to override them **even if they are set in normal state** as you wrote near the end. If this is wanted behaviour, you can close this issue.

**Comment by nacro90** [comment]
Yes, that is wanted. Thanks :heart:
