### ISSUE TITLE
Support typing line numbers directly

### ISSUE THREAD

**Issue by andrewferrier** [nacro90/numb.nvim#6]
`numb.nvim` is a very nice low-friction improvement for NeoVim. Thanks for your work.

However, normally, I get to a specific (numbered) line by just typing the line number, i.e. `23G` , not `:23<CR>` (it's one keystore shorter too!). It would be super-nice if `numb.vim` could operate in that mode also.

**Comment by nacro90** [comment]
Hi, I am very glad to hear that thanks!

I don't think it is a good idea that change the default behaviour of number keys in normal mode. It can be annoying when user intends relative line jump (e.g `10j`) or repetitive motion (e.g `2w`) instead of peeking.

**Comment by andrewferrier** [comment]
That's a good point, I'd actually not thought of that! This makes `numb` less useful to me, as my finger memory has me reach for `23G` rather than `:23<CR>`, but you are definitely correct. Good work anyway!
